FROM existo/postfix:3.4.5


RUN set -x \
	&& yum install -y net-tools \
	&& yum install -y telnet \
	&& yum install -y less

COPY files /

RUN set -x \
	&& cd /etc \
	&& sed 's|^mail\.\*.*|mail\.\* /var/log/postfix/maillog|' -i rsyslog.conf \
	&& mkdir /var/log/postfix \
	&& chown postfix.postfix /var/log/postfix \
	\
	&& chmod 700 /opt/postfix/env

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

