FROM centos:7

LABEL VERSION 2.3.6

RUN set -x \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    && groupadd -g 700 vmail \
    && useradd -d /home/dominios -s /sbin/nologin -g vmail -M -u 700 vmail \
    && groupadd dovecot \
    && groupadd dovenull \
    && useradd -d /opt/dovecot -s /bin/false -g dovecot -M dovecot \
    && useradd -d /opt/dovecot -s /bin/false -g dovenull -M dovenull \
    \
	&& yum -y install gcc \
	&& yum -y install make \
    && yum -y install wget \
    && yum -y install openssl-devel \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install supervisor \
    \
    && cd /usr/local/src \
    && wget https://dovecot.org/releases/2.3/dovecot-2.3.6.tar.gz \
    && tar xzvf dovecot-2.3.6.tar.gz \
    && rm dovecot-2.3.6.tar.gz \
    && cd dovecot-2.3.6 \
    && ./configure \
        --prefix=/opt/dovecot \
        --without-shadow \
        --without-pam \
        --without-gssapi \
        --without-ldap \
        --without-mysql \
        --without-pgsql \
        --without-sqlite \
    \
    && cd /usr/local/src/dovecot-2.3.6 \
    && make \
    && make install \
    \
    && echo PATH=/opt/dovecot/bin/:/opt/dovecot/sbin/:$PATH > /etc/profile.d/path.sh \
    && cp -av /opt/dovecot/share/doc/dovecot/example-config/* /opt/dovecot/etc/dovecot \
    && mkdir /var/log/dovecot \
    && chown dovecot.dovecot /var/log/dovecot \
    \
    && yum -y remove gcc \
    && yum -y remove make \
    && yum -y remove openssl-devel \
    && yum -y remove wget \
    && yum clean all

# COPY etc/ /opt/dovecot/etc
# COPY supervisord.conf /etc/supervisord.conf


# RUN yum -y install net-tools

# RUN ln -s /opt/dovecot/bin/doveadm /usr/bin

# RUN rm -Rf /usr/local/src/dovecot-2.3.6

# RUN mkdir /var/log/dovecot

# Expose 25
# Expose 143
# Expose 110
# Expose 993
# Expose 995

CMD ["/usr/sbin/init"]
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

