FROM postfix:3.4.5

RUN set -x \
	&& yum install -y net-tools \
	&& yum install -y telnet \
	&& yum install -y less

# RUN mkdir /opt/postfix/queue

COPY files /

RUN chmod 700 /opt/postfix/env

# CMD ["/bin/bash", "echo hola"]
# CMD echo "hola ${MULTI_INSTANCE_NAME}"
#CMD ["/bin/bash", "-c", "hola2  ${MULTI_INSTANCE_NAME}"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

# CMD ["/usr/sbin/init"]

# CMD ["/opt/postfix/env"]
