FROM existo/postfix:3.4.5


COPY files /

RUN set -x \
    && echo PATH=/opt/postfix/bin/:$PATH > /etc/profile.d/path.sh \
	&& echo export PATH >> /etc/profile.d/path.sh \
	&& echo PATH=/opt/postfix/bin/:$PATH > /root/.bashrc \
	&& cd /etc \
	&& sed 's|^mail\.\*.*|mail\.\* /var/log/postfix/maillog|' -i rsyslog.conf \
	&& mkdir /var/log/postfix \
	&& chown postfix.postfix /var/log/postfix \
	\
	&& chmod 700 /opt/postfix/env

# Variables de entorno
# MY_HOSTNAME               Nombre del servidor
# SSL                       [yes|no] Si activa o no el SSL
# SASL:                     "yes"
# SMTPS:                    "yes"
# SUBMISSION:               "yes"
# MY_NETWORKS:              127.0.0.1
# VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
# VIRTUAL_MAILBOX_BASE:     /home/dominios
# VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
# VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
# RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
# SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados
# SMTPD_RECIPIENT_RESTRICTIONS


CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

