FROM centos:7

LABEL VERSION 3.4.5

ENV VERSION 3.4.5

RUN set -x \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    && groupadd -g 700 vmail \
    && useradd -d /home/dominios -s /sbin/nologin -g vmail -M -u 700 vmail \
    \
	&& yum -y install gcc \
	&& yum -y install make \
	&& yum -y install m4 \
    && yum -y install wget \
    && yum -y install rsyslog \
    && yum -y install libdb-devel \
    && yum -y install pcre-devel \
    && yum -y install openssl-devel \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install supervisor \
    \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash \
    \
    && cd /usr/local/src \
    && wget http://ftp.uma.es/mirror/postfix/src/official/postfix-3.4.5.tar.gz \
    && tar xzvf postfix-${VERSION}.tar.gz \
    && rm postfix-${VERSION}.tar.gz \
    && cd postfix-${VERSION} \
    \
    && make makefiles CCARGS='-DDEF_CONFIG_DIR=\"/opt/postfix/etc\" \
        -DDEF_COMMAND_DIR=\"/opt/postfix/bin\" \
        -DDEF_DAEMON_DIR=\"/opt/postfix/daemon\" \
        -DDEF_DATA_DIR=\"/opt/postfix/data\" \
        -DDEF_MAILQ_PATH=\"/opt/postfix/bin/mailq\" \
        -DDEF_NEWALIAS_PATH=\"/opt/postfix/bin/newaliases\" \
        -DDEF_QUEUE_DIR=\"/opt/postfix/spool\" \
        -DDEF_SENDMAIL_PATH=\"/usr/sbin/sendmail\" \
        -DUSE_SASL_AUTH \
        -DDEF_SERVER_SASL_TYPE=\"dovecot\" \
        -DHAS_PCRE -I/usr/local/include \
        -DUSE_TLS ' \
        AUXLIBS='-lssl -lcrypto -lpcre' \
    \
    && make \
    && make install -non-interactive \
    && /bin/sh postfix-install -non-interactive \
    \
    && /opt/postfix/bin/newaliases \
    && ln -s /opt/postfix/bin/postmap /usr/local/bin \
    && echo PATH=/opt/postfix/bin/:$PATH > /etc/profile.d/path.sh \
    \
    && yum -y remove gcc \
    && yum -y remove make \
    && yum -y remove m4 \
    && yum -y remove libdb-devel \
    && yum -y remove pcre-devel \
    && yum -y remove openssl-devel \
    && yum -y remove wget \
    && yum clean all \
    && rm -rf /var/cache/yum/*

COPY files /

EXPOSE 25

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

