FROM centos:7

LABEL VERSION 3.4.5

ENV VERSION 3.4.5

RUN set -x \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    \
	&& yum -y install gcc \
	&& yum -y install make \
	&& yum -y install m4 \
    && yum -y install wget \
    && yum -y install rsyslog \
    && yum -y install libdb-devel \
    && yum -y install pcre-devel \
    && yum -y install openssl-devel \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install supervisor \
    \
    && cd /usr/local/src \
    && wget http://ftp.uma.es/mirror/postfix/src/official/postfix-3.4.5.tar.gz \
    && tar xzvf postfix-${VERSION}.tar.gz \
    && rm postfix-${VERSION}.tar.gz \
    && cd postfix-${VERSION}

RUN set -x \
    && cd /usr/local/src/postfix-${VERSION} \
    && make makefiles CCARGS='-DDEF_CONFIG_DIR=\"/opt/postfix/etc\" \
        -DDEF_COMMAND_DIR=\"/opt/postfix/bin\" \
        -DDEF_DAEMON_DIR=\"/opt/postfix/daemon\" \
        -DDEF_DATA_DIR=\"/opt/postfix/data\" \
        -DDEF_MAILQ_PATH=\"/opt/postfix/bin/mailq\" \
        -DDEF_NEWALIAS_PATH=\"/opt/postfix/bin/newaliases\" \
        -DDEF_QUEUE_DIR=\"/opt/postfix/spool\" \
        -DDEF_SENDMAIL_PATH=\"/usr/sbin/sendmail\" \
        -DUSE_SASL_AUTH \
        -DDEF_SERVER_SASL_TYPE=\"dovecot\" \
        -DHAS_PCRE -I/usr/local/include \
        -DUSE_TLS ' \
        AUXLIBS='-lssl -lcrypto -lpcre'

RUN set -x \
    && cd /usr/local/src/postfix-${VERSION} \
    && make

RUN set -x \
    && cd /usr/local/src/postfix-${VERSION} \
    && make install -non-interactive \
    && /bin/sh postfix-install -non-interactive


# RUN set -x \
#     && yum -y install db4-devel \
#     && yum -y install pcre-devel

# RUN set -x \
    # && groupadd dovecot \
    # && groupadd dovenull \
    # && useradd -d /opt/dovecot -s /bin/false -g dovecot -M dovecot \
    # && useradd -d /opt/dovecot -s /bin/false -g dovenull -M dovenull \
    # \
	# && yum -y install gcc \
	# && yum -y install make \
    # && yum -y install wget \
    # && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    # && yum -y install supervisor \
    # \
    # && cd /usr/local/src \
    # && wget https://www.dovecot.org/releases/2.3/dovecot-2.3.2.1.tar.gz \
    # && tar xzvf dovecot-2.3.2.1.tar.gz \
    # && rm dovecot-2.3.2.1.tar.gz \
    # && cd dovecot-2.3.2.1 \
    # && ./configure \
    #     --prefix=/opt/dovecot \
    #     --without-shadow \
    #     --without-pam \
    #     --without-gssapi \
    #     --without-ldap \
    #     --without-mysql \
    #     --without-pgsql \
    #     --without-sqlite \
    # \
    # && cd /usr/local/src/dovecot-2.3.2.1 \
    # && make \
    # && make install \
    # \
    # && yum -y remove gcc \
    # && yum -y remove make \
    # && yum -y remove wget \
        # && rm -rf /var/cache/yum/* \

    # && yum clean all

# COPY etc/ /opt/dovecot/etc
# COPY supervisord.conf /etc/supervisord.conf

# RUN yum -y install net-tools

# RUN ln -s /opt/dovecot/bin/doveadm /usr/bin

# RUN rm -Rf /usr/local/src/dovecot-2.3.2.1

# RUN mkdir /var/log/dovecot

# Expose 24
# Expose 143
# Expose 110
# Expose 993
# Expose 995

CMD ["/usr/sbin/init"]
#CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

