version: '3.7'

services:
  postfix_mx:

    build:
      context: docker/postfix

    ports:
      - "51.91.13.123:25:25"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/dominios:/home/dominios
      - ./etc:/opt/postfix/conf
      - ./logs:/var/log/postfix
      - ./spool.MX:/opt/postfix/spool
      # - ./data.MX:/opt/postfix/data

    environment:
      SSL:                      "mx.ametel.es"
      MULTI_INSTANCE_NAME:      MX
      MY_HOSTNAME:              mx.ametel.es
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        reject_unauth_destination,
        check_client_access hash:/opt/postfix/conf/check_client_access,
        check_helo_access pcre:/opt/postfix/conf/helo_access.pcre,
        reject_non_fqdn_helo_hostname,
        reject_invalid_helo_hostname,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain,
        reject_unauth_pipelining,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unlisted_recipient,
        #       reject_unknown_client_hostname,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        # check_sender_access hash:/opt/postfix/conf/nogreylist,
        #       check_client_access pcre:/opt/postfix/conf/filter_default,
        reject_rbl_client bl.spamcop.net,
        reject_rbl_client zen.spamhaus.org,
        reject_rhsbl_sender dbl.spamhaus.org,
        ##        check_policy_service unix:private/postgrey,
        permit

    networks:
      - localNetwork

  postfix_couk:

    build:
      context: docker/postfix

    ports:
      - "147.135.246.57:25:25"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/dominios:/home/dominios
      - ./etc:/opt/postfix/conf
      - ./logs.COUK:/var/log/postfix
      - ./spool.COUK:/opt/postfix/spool
      # - ./data.COUK:/opt/postfix/data

    environment:
      SSL:                      "test.ametel.co.uk"
      SASL:                     "yes"
      MULTI_INSTANCE_NAME:      "couk"
      MY_HOSTNAME:              mx.ametel.es
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        check_sender_access hash:/opt/postfix/conf/bloquear_envios,
        permit_sasl_authenticated,
        reject

    networks:
      - localNetwork


  postmap:
    image: existo/postfix:3.4.5
    working_dir: /opt/postfix/conf
    entrypoint: "/opt/postfix/bin/postmap"
    volumes:
      - ./etc:/opt/postfix/conf


  dovecot:
    # environment:
    #   IMAP_IP:  localhost
    #   POP3_IP:  localhost

    build:
      context: docker/dovecot

    # depends_on:
    #   - postfix

    environment:
      SSL:                  "test.ametel.co.uk"
      AUTH_DEBUG:           "yes"
      AUTH_DEBUG_PASSWORDS: "yes"

    volumes:
      - /home/dominios:/home/dominios
      # - ./dominios:/home/dominios
      - ./etc:/opt/dovecot/conf
      - ./logs:/var/log/dovecot
      # - ./spool.COUK:/opt/dovecot/spool.COKU
      # - ./data:/opt/postfix/data
      - /etc/letsencrypt:/etc/letsencrypt

    ports:
      - "147.135.246.57:110:110"
      - "147.135.246.57:143:143"
      - "147.135.246.57:993:993"
      - "147.135.246.57:995:995"
      # - target: 110
      #   published: 110
      #   protocol: tcp
      #   mode: host

    networks:
      - localNetwork


networks:
  localNetwork:

