version: '3.7'

services:
  postfix_mx:

    build:
      context: docker/postfix

    ports:
      - "51.91.13.123:25:25"

    volumes:
      - /home/dominios:/home/dominios
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc:/opt/postfix/conf
      - ./log.MX:/var/log/postfix
      - ./spool.MX:/opt/postfix/spool

    environment:
      SSL:                      "mx.ametel.es"
      MULTI_INSTANCE_NAME:      MX
      MY_HOSTNAME:              mx.ametel.es
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
      RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
      # SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        reject_unauth_destination,
        check_client_access hash:/opt/postfix/conf/check_client_access,
        check_helo_access pcre:/opt/postfix/conf/helo_access.pcre,
        reject_non_fqdn_helo_hostname,
        reject_invalid_helo_hostname,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain,
        reject_unauth_pipelining,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unlisted_recipient,
        #       reject_unknown_client_hostname,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        # check_sender_access hash:/opt/postfix/conf/nogreylist,
        #       check_client_access pcre:/opt/postfix/conf/filter_default,
        reject_rbl_client bl.spamcop.net,
        reject_rbl_client zen.spamhaus.org,
        # reject_rhsbl_sender dbl.spamhaus.org,
        ##        check_policy_service unix:private/postgrey,
        permit

    restart: always

    networks:
      - localNetwork

  postfix_couk:

    # https://www.mind-it.info/2014/02/20/change-postfix-master-cf-postconf/

    build:
      context: docker/postfix

    ports:
      - "147.135.246.57:25:25"
      - "147.135.246.57:465:465"
      - "147.135.246.57:587:587"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/dominios:/home/dominios
      - ./etc:/opt/postfix/conf
      - ./log.COUK:/var/log/postfix
      - ./spool.COUK:/opt/postfix/spool

    environment:
      SMTPS:                    "yes"
      SUBMISSION:               "yes"
      SSL:                      "mail.ametel.co.uk"
      SASL:                     "yes"
      MULTI_INSTANCE_NAME:      "couk"
      MY_HOSTNAME:              mail.ametel.co.uk
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
      RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
      SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        check_sender_access hash:/opt/postfix/conf/bloquear_envios,
        permit_sasl_authenticated,
        reject

    restart: always

    networks:
      - localNetwork


  postfix_moy:

    build:
      context: docker/postfix

    ports:
      - "137.74.217.21:25:25"
      - "137.74.217.21:465:465"
      - "137.74.217.21:587:587"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/dominios:/home/dominios
      - ./etc:/opt/postfix/conf
      - ./log.MOY:/var/log/postfix
      - ./spool.MOY:/opt/postfix/spool

    environment:
      SMTPS:                    "yes"
      SUBMISSION:               "yes"
      SSL:                      "mail.moyselec.es"
      SASL:                     "yes"
      MULTI_INSTANCE_NAME:      "moyselec"
      MY_HOSTNAME:              mail.moyselec.es
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
      RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
      SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        check_sender_access hash:/opt/postfix/conf/bloquear_envios,
        permit_sasl_authenticated,
        reject

    restart: always

    networks:
      - localNetwork


  postfix_ametel.cl:

    # https://www.mind-it.info/2014/02/20/change-postfix-master-cf-postconf/

    build:
      context: docker/postfix

    ports:
      - "87.98.227.179:25:25"
      - "87.98.227.179:465:465"
      - "87.98.227.179:587:587"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/dominios:/home/dominios
      - ./etc:/opt/postfix/conf
      - ./log.CL:/var/log/postfix
      - ./spool.CL:/opt/postfix/spool

    environment:
      SMTPS:                    "yes"
      SUBMISSION:               "yes"
      SSL:                      "mail.ametel.cl"
      SASL:                     "yes"
      MULTI_INSTANCE_NAME:      "cl"
      MY_HOSTNAME:              mail.ametel.cl
      MY_NETWORKS:              127.0.0.1
      SMTP_BIND_ADDRESS:        51.91.13.123
      VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
      VIRTUAL_MAILBOX_BASE:     /home/dominios
      VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
      VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
      RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
      SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados

      SMTPD_RECIPIENT_RESTRICTIONS: >
        permit_mynetworks,
        check_recipient_access hash:/opt/postfix/conf/bloquear_destinos,
        check_sender_access hash:/opt/postfix/conf/bloquear_envios,
        permit_sasl_authenticated,
        reject

    restart: always

    networks:
      - localNetwork



  postmap:
    image: existo/postfix:3.4.5
    working_dir: /opt/postfix/conf
    entrypoint: "/opt/postfix/bin/postmap"
    volumes:
      - ./etc:/opt/postfix/conf


  dovecot:

    image: dovecot-existo:2.3.6-1

    environment:
      NAME:                 "ametel.co.uk"
      SSL:                  "mail.ametel.co.uk"
      AUTH_DEBUG:           "no"
      AUTH_DEBUG_PASSWORDS: "no"

    volumes:
      - /home/dominios:/home/dominios
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc:/opt/dovecot/conf
      - ./log:/var/log/dovecot

    ports:
      - "147.135.246.57:110:110"
      - "147.135.246.57:143:143"
      - "147.135.246.57:993:993"
      - "147.135.246.57:995:995"

    restart: always

    networks:
      - localNetwork


  dovecot_moyselec:

    image: dovecot-existo:2.3.6-1

    environment:
      NAME: "moyselec.es"
      SSL:  "mail.moyselec.es"

    volumes:
      - /home/dominios:/home/dominios
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc:/opt/dovecot/conf
      - ./log:/var/log/dovecot

    ports:
      - "137.74.217.21:110:110"
      - "137.74.217.21:143:143"
      - "137.74.217.21:993:993"
      - "137.74.217.21:995:995"

    restart: always

    networks:
      - localNetwork


  dovecot_ametel.cl:

    image: dovecot-existo:2.3.6-1

    environment:
      NAME: "ametel.cl"
      SSL:  "mail.ametel.cl"

    volumes:
      - /home/dominios:/home/dominios
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc:/opt/dovecot/conf
      - ./log:/var/log/dovecot

    ports:
      - "87.98.227.179:110:110"
      - "87.98.227.179:143:143"
      - "87.98.227.179:993:993"
      - "87.98.227.179:995:995"

    restart: always

    networks:
      - localNetwork

networks:
  localNetwork:

