FROM docker.existo.net/httpd:7.2.2

LABEL VERSION roundcube:1.3.10

RUN set -x \
    && yum -y install wget \
    \
    && cd /opt \
    &&  wget https://github.com/roundcube/roundcubemail/releases/download/1.3.10/roundcubemail-1.3.10-complete.tar.gz \
    && tar xzvf roundcubemail-1.3.10-complete.tar.gz \
    && rm roundcubemail-1.3.10-complete.tar.gz \
    && mv roundcubemail-1.3.10 roundcube \
    \
    && yum -y remove wget \
    && yum clean all \
    && rm -Rf /var/cache/yum \
    \
    && echo "" >> /opt/httpd/conf/directory.conf \
    && echo -e "<Directory /opt/roundcube>" >> /opt/httpd/conf/directory.conf \
    && echo -e "\t# Options FollowSymLinks" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllowOverride None" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tOrder allow,deny" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllow from all" >> /opt/httpd/conf/directory.conf \
    && echo -e "</Directory>" >> /opt/httpd/conf/directory.conf \
    && echo "" >> /opt/httpd/conf/directory.conf \
    && echo -e "<Directory /opt/roundcube/config>" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tOrder deny,allow" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tDeny from all" >> /opt/httpd/conf/directory.conf \
    && echo -e "</Directory>" >> /opt/httpd/conf/directory.conf \
    && echo "" >> /opt/httpd/conf/directory.conf \
    \
    && mkdir -p /tmp/roundcube \
    && chown web.web /tmp/roundcube

COPY files/ /
