FROM existo/php:7.2.19

LABEL HTTPD 2.4.34
LABEL PHP 7.2.19
LABEL PHPMYADMIN 4.8.2

COPY files/ /

RUN set -x \
    && groupadd -g 600 web \
    && useradd -d /home/web -s /bin/false -g web -M -u 600 web \
    \
    && yum -y install wget \
    #&& yum -y install ImageMagick \
    # Necesarios para wkhtmltopdf
    #&& yum -y install poppler-utils \
    #&& yum -y install openssl \
    #&& yum -y install xorg-x11-fonts-75dpi \
    #&& yum -y install xorg-x11-fonts-Type1 \
    # Caracteres japoneses para wkhtml
    #&&  yum -y install wqy-microhei-fonts \
    #&& fc-cache -f -v \
    \
    && cd /tmp \
    && curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" \
    && python get-pip.py \
    && rm /tmp/get-pip.py \
    && pip install -U certbot \
    && mkdir -p /opt/certbot \
    && echo -e ""  >> /opt/httpd/conf/directory.conf \
    && echo -e ""  >> /opt/httpd/conf/directory.conf \
    && echo -e "<Directory \"/opt/certbot/.well-known\">" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllowOverride None" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tOrder allow,deny" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllow from all" >> /opt/httpd/conf/directory.conf \
    && echo -e "</Directory>" >> /opt/httpd/conf/directory.conf \
    && echo -e ""  >> /opt/httpd/conf/directory.conf \
    && echo "#!/bin/bash" >> /usr/local/bin/certbot \
    && echo "" >> /usr/local/bin/certbot \
    && echo "/usr/bin/certbot certonly --webroot -w /opt/certbot \$@" >> /usr/local/bin/certbot \
    && chmod 755 /usr/local/bin/certbot \
    && echo -e ""  >> /opt/httpd/conf/alias.conf \
    && echo -e ""  >> /opt/httpd/conf/alias.conf \
    && echo -e "Alias \"/.well-known\" \"/opt/certbot/.well-known\""  >> /opt/httpd/conf/alias.conf \
    && echo -e ""  >> /opt/httpd/conf/alias.conf \
    \
    && cd /opt \
    &&  wget https://files.phpmyadmin.net/phpMyAdmin/4.8.2/phpMyAdmin-4.8.2-all-languages.tar.gz \
    && tar xzvf phpMyAdmin-4.8.2-all-languages.tar.gz \
    && rm phpMyAdmin-4.8.2-all-languages.tar.gz \
    && cp -r phpMyAdmin-4.8.2-all-languages/. phpMyAdmin \
    && rm -R phpMyAdmin-4.8.2-all-languages \
    && echo -e ""  >> /opt/httpd/conf/directory.conf \
    && echo -e "<Directory \"/opt/phpMyAdmin\">" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tphp_value memory_limit 256M" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllowOverride None" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tOptions None" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tOrder allow,deny" >> /opt/httpd/conf/directory.conf \
    && echo -e "\tAllow from all" >> /opt/httpd/conf/directory.conf \
    && echo -e "</Directory>" >> /opt/httpd/conf/directory.conf \
    && echo -e ""  >> /opt/httpd/conf/directory.conf \
    \
    && cd /tmp \
    #&& wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.centos7.x86_64.rpm \
    #&& rpm -i wkhtmltox-0.12.5-1.centos7.x86_64.rpm \
    #&& rm wkhtmltox-0.12.5-1.centos7.x86_64.rpm \
    && yum -y remove wget \
    && yum clean all \
    \
    && mkdir -p /home/no-server \
    && mkdir -p /tmp/pdfs \
    && mkdir -p /tmp/uploads \
    && mkdir -p /tmp/sesiones \
    #&& touch /var/log/email.log \
    && chown web.web /home/no-server \
    && chown web.web /tmp/pdfs /tmp/uploads /tmp/sesiones
    # && chown web.web /var/log/http/php.log \
    # && chown web.web /var/log/httpd
    #&& chown web.web /var/log/email.log \
    #&& chmod 755 /usr/bin/mysqldev


CMD /opt/httpd/start.sh
