FROM docker.existo.net/http:7.2.1

LABEL VERSION roundcube:1.3.10

#COPY files/ /

RUN set -x \
    && yum -y install wget \
    \
    && cd /opt \
    &&  wget https://github.com/roundcube/roundcubemail/releases/download/1.3.10/roundcubemail-1.3.10-complete.tar.gz \
    && tar xzvf roundcubemail-1.3.10-complete.tar.gz -C /opt/roundcube \
    \
    && yum -y remove wget \
    && yum clean all \
    && rm -rf /var/cache/yum

