FROM dovecot:2.3.6


RUN set -x \
	&& yum install -y net-tools \
	&& yum install -y telnet \
	&& yum install -y less

# RUN mkdir /opt/postfix/queue

COPY files /

# RUN chmod 700 /opt/postfix/env

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

