FROM centos:7

ENV VERSION 2.4.34

RUN set -x \
	&& groupadd -g 48 apache \
	&& useradd -u 48 -g apache -d /opt/httpd -s /sbin/nologin -M apache \
	&& mkdir /var/log/httpd \
	&& chown apache.apache /var/log/httpd \
	\
	&& yum -y install perl \
	\
	&& yum -y install pcre-devel \
	&& yum -y install expat-devel \
	&& yum -y install gcc \
	&& yum -y install openssl-devel \
	&& yum -y install make \
	&& yum -y install wget \
	\
	&& cd /usr/local/src \
	&& wget http://apache.uvigo.es//apr/apr-1.6.3.tar.gz \ 
	&& tar xzvf apr-1.6.3.tar.gz \
	&& rm apr-1.6.3.tar.gz \
	&& cd apr-1.6.3 \
	&& ./configure \ 
		--prefix=/opt/apr-1.6.3 \
	&& make \
	&& make install \
	&& cd .. \
	&& rm -Rf apr-1.6.3 \
	\
	&& wget http://apache.uvigo.es//apr/apr-util-1.6.1.tar.gz \ 
	&& tar xzvf apr-util-1.6.1.tar.gz \
	&& rm apr-util-1.6.1.tar.gz \
	&& cd apr-util-1.6.1 \
	&& ./configure \
		--prefix=/opt/apr-util-1.6.1 \
		--with-apr=/opt/apr-1.6.3 \
	&& make \
	&& make install \
	&& cd .. \
	&& rm -Rf apr-util-1.6.1 \
	\
	&& wget http://apache.rediris.es//httpd/httpd-${VERSION}.tar.gz \
	&& tar xzvf httpd-${VERSION}.tar.gz \
	&& rm httpd-${VERSION}.tar.gz \
	&& cd httpd-${VERSION} \
	&& ./configure --prefix=/opt/httpd \
			--with-apr=/opt/apr-1.6.3 \
			--with-apr-util=/opt/apr-util-1.6.1 \
			--enable-ssl \
 	&& make \
 	&& make install \
	&& cd .. \
	&& rm -Rf httpd-${VERSION} \
	&& mkdir /home/web \
	\
	&& yum -y remove pcre-devel \
	&& yum -y remove expat-devel \
	&& yum -y remove gcc \
	&& yum -y remove openssl-devel \
	&& yum -y remove make \
	&& yum -y remove wget 

COPY httpd.conf \
	directory.conf \
	alias.conf \
	modules.conf \
	/opt/httpd/conf/

EXPOSE 80

CMD /opt/httpd/bin/apachectl start -DFOREGROUND


