FROM apache:2.4.34

COPY files/ /

RUN set -x \
    && yum -y install libxml2-devel \
    && yum -y install freetype-devel \
    && yum -y install libjpeg-devel \
    && yum -y install libpng-devel \
    && yum -y install gd-devel \
    && yum -y install zlib-devel \
    && yum -y install bzip2-devel \
    && yum -y install curl-devel \
    && yum -y install libxslt-devel \
    && yum -y install libicu-devel \
    && yum -y install install openssl-devel \ 
    && yum -y install gcc \  
    && yum -y install gcc-c++ \
    && yum -y install autoconf \
    && yum -y install make \
    && yum -y install wget \
    \
    && yum -y install bison \
    \
    && curl http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/r/re2c-0.14.3-2.el7.x86_64.rpm --output re2c-0.14.3-2.el7.x86_64.rpm \
    && rpm -Uvh re2c-0.14.3-2.el7.x86_64.rpm \
    && rm re2c-0.14.3-2.el7.x86_64.rpm \
    \
    && cd /usr/local/src \
    && wget http://es1.php.net/get/php-7.1.19.tar.gz/from/this/mirror -O php-7.1.19.tar.gz \
    && tar xzvf php-7.1.19.tar.gz \
    && rm php-7.1.19.tar.gz \
    \
    && cd php-7.1.19 \
    && ./configure \
        --prefix=/opt/php \
        --with-config-file-path=/opt/php/etc \
        --with-apxs2=/opt/httpd/bin/apxs \
        --with-mysqli=mysqlnd \
        --with-iconv \
        --enable-mbstring \
        --with-curl \
        --with-gd \
        --with-png-dir \
        --with-jpeg-dir \
        --with-freetype-dir \
        --with-zlib-dir \
        --enable-inline-optimization \
        --without-sqlite3 \
        --without-pdo-sqlite \
        --with-gettext \
        --enable-ftp \
        --enable-zip \
        --disable-cgi \
        --with-openssl \
        --with-pdo-mysql \
        --enable-soap \
        --with-bz2 \
        --with-xsl \
        --enable-bcmath \
        --enable-intl \
        --enable-exif \
        --enable-sockets \
    && make \
    && make install \
    && cd .. \
    && rm -Rf php-7.1.19 \
    \
    && wget https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.30/GraphicsMagick-1.3.30.tar.gz \
    && tar xzvf GraphicsMagick-1.3.30.tar.gz \
    && rm GraphicsMagick-1.3.30.tar.gz \
    && cd GraphicsMagick-1.3.30 \
    && ./configure --prefix=/opt/graphics-magick-1.3.30 --enable-shared \
    && make \
    && make install \
    && cd .. \
    && rm -Rf GraphicsMagick-1.3.30 \
    \    
    && yes "/opt/graphics-magick-1.3.30" | /opt/php/bin/pecl install gmagick-2.0.5RC1 \
    \
    && mkdir /tmp/sesiones \
    && chown apache.apache /tmp/sesiones \
    && touch /var/log/php.log \
    && chown apache.apache /var/log/php.log \
    \
    && yum -y remove libxml2-devel \
    && yum -y remove freetype-devel \
    && yum -y remove libjpeg-devel \
    && yum -y remove libpng-devel \
    && yum -y remove gd-devel \
    && yum -y remove zlib-devel \
    && yum -y remove bzip2-devel \
    && yum -y remove curl-devel \
    && yum -y remove libxslt-devel \
    && yum -y remove libicu-devel \
    && yum -y remove remove openssl-devel \
    && yum -y remove gcc \  
    && yum -y remove gcc-c++ \
    && yum -y remove make \
    && yum -y remove autoconf \
    && yum -y remove wget 



