FROM existo/postfix:3.4.5


COPY files /

RUN set -x \
	&& mkdir /var/log/postfix \
	&& chown postfix.postfix /var/log/postfix \
	\
	&& chmod 700 /opt/postfix/env

# Variables de entorno
# MY_HOSTNAME               Nombre del servidor
# SSL                       [yes|no] Si activa o no el SSL
# SASL:                     "yes"
# SMTPS:                    "yes"
# SUBMISSION:               "yes"
# MY_NETWORKS:              127.0.0.1
# VIRTUAL_MAILBOX_DOMAINS:  hash:/opt/postfix/conf/domains
# VIRTUAL_MAILBOX_BASE:     /home/dominios
# VIRTUAL_MAILBOX_MAPS:     hash:/opt/postfix/conf/users
# VIRTUAL_ALIAS_MAPS:       hash:/opt/postfix/conf/alias
# RECIPIENT_BCC_MAPS:       regexp:/opt/postfix/conf/bcc_recibidos
# SENDER_BCC_MAPS:          regexp:/opt/postfix/conf/bcc_enviados
# SMTPD_RECIPIENT_RESTRICTIONS
# SMTPD_MILTERS:             unix:private/existoMilter, inet:localhost:8891
# NON_SMTPD_MILTERS:         unix:private/existoMilter, inet:localhost:8891
# AUTORESPUESTA:             [yes|no] Si activa o no la autorespuesta
# DEBUG_LEVEL:               [0-10?]
# DEBUG_IP:                  IP

WORKDIR /opt/postfix

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

